CREATE TABLE MENU (
	RESTAURANT_ID INT NOT NULL ,
	FOOD_ID INT NOT NULL,
	SEQUENCE INT,
	CONSTRAINT FK_MENU_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(ID),
	CONSTRAINT FK_MENU_FOOD FOREIGN KEY (FOOD_ID) REFERENCES FOOD(ID)
);