CREATE TABLE CAROUSEL (
	ID INT PRIMARY KEY  NOT NULL AUTO_INCREMENT ,
	CAROUSEL_ID INT NOT NULL,
	CAROUSEL_TITLE VARCHAR (45) NOT NULL,
	CAROUSEL_SUBTITLE VARCHAR (45) NOT NULL,
	CAROUSEL_VISIBILITY INT NOT NULL
);