CREATE TABLE PARKING_PLACES(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	PARKING_PLACE_ID INT (45) NOT NULL,
	PARKING_LOCATION VARCHAR (45) NOT NULL,
	PARKING_AVAILABLE TINYINT (1) NOT NULL,
	CONSTRAINT FK_PLACES_PARKING FOREIGN KEY (PARKING_PLACE_ID) REFERENCES PARKING (ID)
	);