CREATE TABLE USERS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,	
	ID_USER INT (45) NOT NULL,
	NAME_USER VARCHAR (45) NOT NULL,
	USER_PHONE VARCHAR (25) NOT NULL,
	USER_PHOTO VARCHAR (45) NOT NULL,
	USER_TASTES VARCHAR (255)NOT NULL,
	USER_NOTIFICATIONS TINYINT (1) NOT NULL,
	USER_VISIBILITY INT NOT NULL
);